workspace:
  base: /hubot
  path: src/github.com/ichiaohsu/mmhubot
pipeline:
  start_slack:
    image: plugins/slack
    channel: ground_control
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    template: >
      *start* building *{{repo.name}}*.
      *{{build.author}}* give *{{build.branch}}* a little push.
    when:
      event: [push]
  builds:
    image: node
    commands:
    - npm install
    when:
      event: [push]
      branch: [prod]
  publish:
    image: plugins/gcr
    repo: mirrormedia-1470651750304/${DRONE_REPO_NAME}
    tag: ${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER}
    environment:
      - DOCKER_LAUNCH_DEBUG=true
    secrets: [google_credentials]
    when:
      event: [push]
  finish_slack:
    image: plugins/slack
    channel: ground_control
    secrets: [slack_webhook]
    username: drone
    icon_url: https://avatars2.githubusercontent.com/u/2181346?s=200&v=4
    when:
      status: [success, failure]
      event: [push]
    template: >
      {{#success build.status}}
        Build<${DRONE_BUILD_LINK}|#{{build.number}}> *success* ${DRONE_REPO_NAME}:${DRONE_COMMIT_AUTHOR}_${DRONE_COMMIT_BRANCH}_${DRONE_BUILD_NUMBER} was well served.
        Check out our new <https://gcr.io/mirrormedia-1470651750304/readr-restful|rest>
      {{else}}
        Houston, we have a problem. Build <${DRONE_BUILD_LINK}|#{{build.number}}> failed. Fix me please, {{build.author}}
      {{/success}}